url: ws://localhost:6700/
names: []
admins: []
groups: []
apps:
  daily-news:
    groups: []
  moyu:
    groups: []
  pcr-gacha:
    pool: BL
  setu:
    apikey: example_key
    r18: 0
    maxWidth: 1000
    maxHeight: 1000
    quality: 60
